provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  uptime:
    lang: python3
    handler: ./uptime
    image: alexellis2/uptime:latest

  pbkdf2:
    lang: node10-express
    handler: ./pbkdf2
    image: pbkdf2:latest
